### ISSUE TITLE
The other party can't see the quoted text

### ISSUE THREAD

**Issue by bolasblack** [wireapp/wire-web-packages#1654] opened 2019-03-19 01:35 UTC
Hi, I'm trying follow [packages/core/src/demo/sender.js](https://github.com/wireapp/wire-web-packages/blob/master/packages/core/src/demo/sender.js#L162) to write a tool can reply some message, then I found the be replied side can not see the quoted text:

<img width="332" alt="图片" src="https://user-images.githubusercontent.com/382011/54573812-c70a5080-4a28-11e9-8781-e958884fe0c1.png">

Here is my code, `wirePayloadBundle` is come from `this.wireAccount.on(PayloadBundleType.TEXT,`

```ts
    const textPayload = this.wireAccount
      .service!.conversation.createText(string)
      .withQuote(
        {
          quotedMessageId: wirePayloadBundle.id,
          content: wirePayloadBundle.content as TextContent,
        },
        wirePayloadBundle.timestamp,
      )
      .build()
    return this.wireAccount
      .service!.conversation.send(wirePayloadBundle.conversation, textPayload)
      .then(val => debug(`Sent text with id ${val.id}`))
```

This issue is because I am missing some steps in the implementation?

**Comment by ffflorian** [comment] 2019-03-29 11:17
Hi @bolasblack, this is not your fault, I can reproduce this.

**Comment by bolasblack** [comment] 2019-03-29 12:15
@ffflorian It’s great to get your reply, thank you.

**Comment by ffflorian** [comment] 2020-01-16 11:33
Hey @bolasblack, we just merged https://github.com/wireapp/wire-web-packages/pull/2762 and finally fixes quotes in the core! :tada:

The new API looks like this:

```ts
// given incomingMessage is a TextMessage or something similar (see QuotableMessage)

const textPayload = account.service!.conversation
  .createText(string)
  .withQuote(incomingMessage as QuotableMessage)
  .build();

return account.service!.conversation
  .send(incomingMessage.conversation, textPayload)
  .then(sentMessage => console.log(`Sent message with ID "${sentMessage.id}".`));
```

**Closed by ffflorian** 2020-01-16 11:33 UTC
Labels: type: bug
